#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
yarn check-format ||
(
  echo '🤢🤮🤢🤮 Your styling looks disgusting. 🤢🤮🤢🤮
          Prettier Check Failed. Run npm run format, add changes and try to commit again.'
  false
)

# Check ESLint Standards
yarn check-lint ||
(
  echo '😤🏀👋😤 Get that weak s***t out of here! 😤🏀👋😤 
          ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

# Check tsconfig standards
yarn check-types ||
(
  echo '👀🤅👀 Something is wrong with your typescript. 👀🤅👀
          Typescript Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

# build
yarn build ||
(
  echo '👀🤅👀 Something is wrong with your build. s👀🤅👀
          Build Check Failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

# if everything passes... Now we can commit
echo '✅✅✅ You win this time... I am committing this now. ✅✅✅'
